
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int CHARLITERAL = 45;
  public static final int GREATERTHAN = 21;
  public static final int DIVIDE = 16;
  public static final int INCREMENT = 12;
  public static final int CHAR = 40;
  public static final int PARENTHASIS_CLOSE = 32;
  public static final int UMINUS = 50;
  public static final int UPLUS = 49;
  public static final int LESSTHAN_OR_EQUAL = 22;
  public static final int NOTEQUAL = 24;
  public static final int INT = 41;
  public static final int PRINTLN = 11;
  public static final int BRACKET_CLOSE = 36;
  public static final int MINUS = 18;
  public static final int GREATERTHAN_OR_EQUAL = 23;
  public static final int DECREMENT = 13;
  public static final int FLOATLITERAL = 48;
  public static final int NOT = 14;
  public static final int SEMICOLON = 29;
  public static final int AND = 5;
  public static final int LESSTHAN = 20; 
  public static final int OR = 6;
  public static final int BOOL = 44;
  public static final int COMMA = 30;
  public static final int CLASS = 2;
  public static final int PLUS = 17;
  public static final int MULTIPLY = 15;
  public static final int ASSIGN = 37; 
  public static final int IF = 25;
  public static final int ID = 3;
  public static final int PARENTHASIS_OPEN = 31;
  public static final int EOF = 0;
  public static final int RETURN = 28;
  public static final int EQUAL = 19;
  public static final int TRUE = 7;
  public static final int error = 1;
  public static final int CURLY_BRACKET_CLOSE = 34;
  public static final int VOID = 43;
  public static final int BRACKET_OPEN = 35;
  public static final int INTLITERAL = 47;
  public static final int COLON = 38;
  public static final int ELSE = 26;
  public static final int READ = 9;
  public static final int CURLY_BRACKET_OPEN = 33;
  public static final int FINAL = 39;
  public static final int WHILE = 27;
  public static final int FLOAT = 42;
  public static final int QUESTION = 4;
  public static final int STRINGLITERAL = 46;
  public static final int FALSE = 8;
  public static final int PRINT = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "ID",
  "QUESTION",
  "AND",
  "OR",
  "TRUE",
  "FALSE",
  "READ",
  "PRINT",
  "PRINTLN",
  "INCREMENT",
  "DECREMENT",
  "NOT",
  "MULTIPLY",
  "DIVIDE",
  "PLUS",
  "MINUS",
  "EQUAL",
  "LESSTHAN",
  "GREATERTHAN",
  "LESSTHAN_OR_EQUAL",
  "GREATERTHAN_OR_EQUAL",
  "NOTEQUAL",
  "IF",
  "ELSE",
  "WHILE",
  "RETURN",
  "SEMICOLON",
  "COMMA",
  "PARENTHASIS_OPEN",
  "PARENTHASIS_CLOSE",
  "CURLY_BRACKET_OPEN",
  "CURLY_BRACKET_CLOSE",
  "BRACKET_OPEN",
  "BRACKET_CLOSE",
  "ASSIGN",
  "COLON",
  "FINAL",
  "CHAR",
  "INT",
  "FLOAT",
  "VOID",
  "BOOL",
  "CHARLITERAL",
  "STRINGLITERAL",
  "INTLITERAL",
  "FLOATLITERAL",
  "UPLUS",
  "UMINUS"
  };
}

